### ISSUE TITLE
TX_Decode failing for File Transfer Abort at PD.

### ISSUE THREAD

**Issue by surendersampath** [goToMain/libosdp#100] opened 2022-12-09 14:01 UTC
**Describe the bug**
PD does not handle the incoming FILE TX command from CP with flag set as `OSDP_CMD_FILE_TX_FLAG_CANCEL` .
Decode fails as the length is lesser than expected.
-------------At PD.
![image](https://user-images.githubusercontent.com/44113702/206717695-3f26352d-2443-4eca-94ec-d8119949c56f.png)

-------------At CP.
![image](https://user-images.githubusercontent.com/44113702/206743967-5e5b180b-61cb-4e16-86fa-99923192e6cd.png)

**Expected behavior**
PD to handle the the file transfer command with `OSDP_CMD_FILE_TX_FLAG_CANCEL` .
**Observed behavior**
A description of what happened.

**Additional context**
I'm using the below code snipped to abort an on-going file transfer. 
```
// Function to Abort File Transfer

bool xAbortTransfer(eOsdpFileTypes xFileType)
{
    bool xStatus = false;
    struct osdp_cmd xAbortCommand;
    xAbortCommand.id = OSDP_CMD_FILE_TX;
    xAbortCommand.file_tx.id = xFileType;
    xAbortCommand.file_tx.flags = OSDP_CMD_FILE_TX_FLAG_CANCEL;    
    xStatus = ( osdp_cp_send_command( ctx, 0, &xAbortCommand ) == 0 ) ? true : false;

    return xStatus;
}
```

**Additional context**

- My use case is to perform an software update between `CP `and `PD`. Binary is sent to `CP` via OTA AND `CP` forwards it.
- I transfer two files between CP and PD with different file ID's. One is Signature. Second one is the actual binary. The signature is used to validate the binary and update accordingly.

Sequence is :
1. The sequence happens such that send the first file with signature and wait for it to complete. Then Starts sending the second file (binary).
2. The signature is cached in the RAM while the binary is stored onto the flash memory. This is by decided by the file ID.
3. During the transmission of second file, the CP wants to abort an on going-transfer.
4. CP sends the file TX command as you suggested in `libosdp`.
5. PD sends an NAK due to mismatch in length as shown in the screenshots. **It does not reset the file state here.**
6. CP starts polling PD again.
7. Step 1 is initiated again by the CP to perform an Software update. However, PD still thinks transfer for Second file is still on going or `OSDP_FILE_INPROG `. 

Suggested FIX : Add `file_state_reset(f);` in the TX_Decode if any error(such as length mistmatch) occurs?

**Comment by sidcha** [comment] 2022-12-10 16:22
> PD does not handle the incoming FILE TX command from CP with flag set as `OSDP_CMD_FILE_TX_FLAG_CANCEL`.

`OSDP_CMD_FILE_TX_FLAG_CANCEL` is not sent to the PD, it is consumed by CP to make the decision of sending the ABORT command. When the CP receives a command that has the cancel bit set, and no transfer is in progress (or the file ID does not match) we [fail the command](https://github.com/goToMain/libosdp/blob/master/src/osdp_file.c#L290)!

So, I suspect something else is causing the failure. What do you need to do to reproduce this issue? The best thing to do is to write a unit test that can reproduce this issue (everything needed to write such a test can be found [here](https://github.com/goToMain/libosdp/blob/master/tests/pytest/test_file_tx.py)).

> Suggested FIX : Add file_state_reset(f); in the TX_Decode if any error(such as length mistmatch) occurs?

Since the failure is between LibOSDP CP <==> PD, I'd prefer to root cause and fix the bug properly rather than mask the issue by fixing the symptom with file_state_reset().

**Comment by surendersampath** [comment] 2022-12-10 22:33
Thanks for looking into this. I'll try and re-create this issue using your unit test set up.

**Comment by sidcha** [comment] 2023-01-17 12:46
@surendersampath, I have a potential fix for this issue. For now, I'm closing this issue but feel free to re-open if you can still reproduce it.

**Closed by sidcha** 2023-01-17 12:46 UTC
